version: '2'
services:
  solr:
    image: mangothecat/rcloud-solr:latest
    ports:
      - "8984:8983"
  solr2:
    image: mangothecat/rcloud-solr:latest
    ports:
      - "8985:8983"
  rstudio:
    image: rcsolr-rstudio
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio/rcloud.solr
